package view.settings;

import javax.swing.*;
import java.awt.*;

public class SettingIntruderPanel {
    private JPanel intruderPanel;

    public JPanel getIntruderPanel() {
        return intruderPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        intruderPanel = new JPanel();
        intruderPanel.setLayout(new CardLayout(0, 0));
        final JLabel label1 = new JLabel();
        label1.setText("INTRUDER PANEL");
        intruderPanel.add(label1, "Card1");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return intruderPanel;
    }
}
